version: '3.8'
services:
  web:
    image: webdevops/php-apache:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: biarms/mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
        - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

